name: Echo Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello, GitHub Actions!"
